project:
  type: book

book:
  title: "Master de spécialisation en Gestion des Risques et Catastrophes à l'ére de l'Anthropocène (GRCA) : prise de notes, synthèse des outils et TFE"
  author: "NEBIE Gaston Cyrille"
  date: "today"
  cover-image: images/logo.png
  language: fr       # <-- ajoute cette ligne
  
  chapters:
    - index.qmd
    - part: "Administration"
      chapters:
        - 00_Admin/historique.qmd
        - 00_Admin/enseignants.qmd
        - 00_Admin/programme.qmd
    - part: "Cours"
      chapters:
        - 01_Cours/RISQ2014_introduction.qmd
        - 01_Cours/ENVT0846_anthropocene.qmd
        - 01_Cours/RISQ2015_risques_naturels.qmd
        - 01_Cours/RISQ2016_tech_technologiques.qmd
        - 01_Cours/RISQ2117_sanitaires.qmd
        - 01_Cours/RISQ2018_SIG_Teledection.qmd
        - 01_Cours/ENVT3124_R_intro.qmd
        - 01_Cours/RISQ2019_alerte_precoce.qmd
        - 01_Cours/RISQ2020_amenagement_prevention.qmd
        - 01_Cours/ENVT0010_seminaire_integre.qmd
        - 01_Cours/RISQ2029_soft_skills.qmd
        - 01_Cours/RISQ2025_migrations_env.qmd
        - 01_Cours/RISQ2030_gouvernance_resilience.qmd
    - part: "Outils"
      chapters:
        - 02_Tools/R_intro.qmd
        - 02_Tools/SIG.qmd
        - 02_Tools/EarlyWarning.qmd
    - part: "Pays & Applications"
      chapters:
        - 06_Pays_Cibles/Burkina_Faso/contexte.qmd
        - 06_Pays_Cibles/Burkina_Faso/application_cours.qmd
        - 06_Pays_Cibles/Burkina_Faso/donnees.qmd
        - 06_Pays_Cibles/Autres_pays/Niger.qmd
        - 06_Pays_Cibles/Autres_pays/Mali.qmd
    - part: "Veille"
      chapters:
        - 07_Veille/articles.qmd
        - 07_Veille/actualites.qmd
        - 07_Veille/politiques.qmd
        - 07_Veille/alertes.qmd
    - part: "TFE"
      chapters:
        - 05_TFE/brainstorming.qmd
        - 05_TFE/plan_travail.qmd
        - 05_TFE/notes_recherche.qmd
        - 05_TFE/draft.qmd
    - part: "aaaaaaaaa"
      chapters:
        - 08_culture-generale/cartographie des structures-GRCA.qmd

bibliography: references.bib

format:
  html:
    toc: true
    theme: cosmo
    number-sections: true
    code-tools: true
    logo: images/logo.png  
    lang: fr 
  pdf:
    lang: fr
    documentclass: scrreprt
    include-in-header: header.tex        # Optionnel pour personnaliser plus le PDF

execute:
  freeze: auto

editor: visual

