---
title: "Conférences & Colloques"
tags: ["opportunites","conferences"]
application_bf: true
---

## Salon des mertiers de l'environnement

### Bienvenue et mot d'ouverture

Le jeudi 25 septembre 2025, de 13h00 à 15h30 minutes s'est tenu l'atelier du salon des métiers de l’environnement au campaus d'A rlon.

Mot de bienvenue du Président du département des sciences et de gestion de l'environnement (Arlon campus environnrment) Bernard Tychon.

- Campus Arlon, plus petit de campus des campus de Uliége. 

Trounée vers :

- develloepement durable,
- transition écologique dans le contexte de l'anthropocène.

L'approche adopté est interdisciplinaire et  transdisciplinaire. Quatre équipe de recherche :

Une palteforme de  arlon'envirolab (https://www.arlonenvirolab.uliege.be/cms/c_12662380/fr/arlon-envirolab)

 4 master dont deux en spécialisation :
 
- Le master en gestion de l'envrionnement à 2 programmes : une exclusivement à Liége et l'autre en coenseignement avec le luxembourg.
 
- Master NEXUS

- Master GRCA

- Master en agroécologie.
(https://www.campus.uliege.be/cms/c_9038320/fr/arlon)

Les sciences de l'environnement on assez de perspectives.

Permettre aux étudiants de rencontrer des professionnels de l'environnement à travers :

- présentation
- salon interactif

### La deuxième phase les interventions des sctu

#### ISSeP

présentation faite par responsbale communication à ISSeP : Institut Scientifique : sentinelle de l'environnement en Wallonie. Service public avec 10% de fonds du privée. Surveillance de l'environnement en wallonie, mais pas dans

2 sites d'exploitations 
www.issep.be

https://www.wallonie.be/fr
forem.be

la collaboration avec les pays voisin, pour la collecte de données transfrontalier se faire via des projets de recherche.

### ODOMETRIC

Laboratoire et bureau d'étude.
Slongan : PRENONS SOIN DE L'AIR QUE NOUS RESPIRONS

- Intérgration au sein de CSD ingénieurs: sol, dépollution, élonienne, biodiversité, airs er ordeurs, environnement (EIE, permitting)

 comment est réalisé la modélisation complexes : https://www.programmes.uliege.be/cocoon/20252026/cours/ENVT0902-1.html https://odometric.com/

### SIX ingénieurs conseils et architectes

https://www.six-eng.eu/

Existe depuis 2024, 

- Départements techniques  spéciales 
-Departesments energie 

### Contrat de rivière semois-chers, ASBL

https://www.semois-chiers.be/


Mettre tous les acteurs autours de la table de gestion de l'eau.

14 contrats de rivières dans ka wallonie

un points noirs : ouvrage, zone de rejet, présence de déchet, erosion (documentés au mieux ceci) ... https://www.crvesdre.be/actions/etat-des-lieux

### AQUALE

Depuis 1992 : wallonie-belgique, europe, reste du monde
https://aquale.com/

Lévènement de 2021 sur les innondations de juilles 2021  sur la verse... a faire evoluer leur attributions


